#include 	"r_cg_macrodriver.h"
#include    "lib_rs019.h"

//定义各个IO口
#define IO_BEEP_DIR_OUT          PORT12OutputConfig(BIT5)
#define IO_BEEP_1                PORT12SetBit(BIT5)
#define IO_BEEP_O                PORT12ClearBit(BIT5)

#define IO_M_SLEEP_DIR_OUT          PORT4OutputConfig(BIT4);PMC4ClearBit(BIT4)
#define IO_M_SLEEP_1                PORT4SetBit(BIT4)
#define IO_M_SLEEP_0                PORT4ClearBit(BIT4)
#define IO_M_CTRL1_DIR_OUT          PORT4OutputConfig(BIT3);PMC4ClearBit(BIT3)
#define IO_M_CTRL1_1                PORT4SetBit(BIT3)
#define IO_M_CTRL1_0                PORT4ClearBit(BIT3)
#define IO_M_CTRL2_DIR_OUT          PORT4OutputConfig(BIT2);PMC4ClearBit(BIT2)
#define IO_M_CTRL2_1                PORT4SetBit(BIT2)
#define IO_M_CTRL2_0                PORT4ClearBit(BIT2)
#define IO_M_POW_DIR_OUT     PORT6OutputConfig(BIT1)
#define IO_M_POW_1           PORT6SetBit(BIT1)
#define IO_M_POW_0           PORT6ClearBit(BIT1)
#define IO_M_DETECT1_DIR_IN      PORT12InputConfig(BIT6)
#define IO_M_DETECT1_READ        PORT12ReadBit(BIT6)
#define IO_M_DETECT2_DIR_IN      PORT12InputConfig(BIT7)
#define IO_M_DETECT2_READ        PORT12ReadBit(BIT7)

#define IO_CARD_BSL_READ            PORT13ReadBit(BIT7)
#define IO_CARD_POWCHECK_DIR_IN     PORT6InputConfig(BIT0)
#define IO_CARD_POWCHECK_READ       PORT6ReadBit(BIT0)
#define IO_CARD_POW_CON_DIR_OUT     PORT1OutputConfig(BIT1);PMC1ClearBit(BIT1);PFSEG4ClearBit(BIT5)
#define IO_CARD_POW_CON_1           PORT1SetBit(BIT1)
#define IO_CARD_POW_CON_0           PORT1ClearBit(BIT1)
#define IO_IIC_CARD_RST_DIR_OUT     PORT1OutputConfig(BIT3);PMC1ClearBit(BIT3);PFSEG4ClearBit(BIT7)
#define IO_IIC_CARD_RST_1           PORT1SetBit(BIT3)
#define IO_IIC_CARD_RST_0           PORT1ClearBit(BIT3)
#define IO_IIC_CARD_SCL_DIR_OUT     PORT1OutputConfig(BIT4);PFSEG5ClearBit(BIT0)
#define IO_IIC_CARD_SCL_1           PORT1SetBit(BIT4)
#define IO_IIC_CARD_SCL_0           PORT1ClearBit(BIT4)
#define IO_IIC_CARD_SDA_DIR_OUT     PORT1OutputConfig(BIT2);PMC1ClearBit(BIT2);PFSEG4ClearBit(BIT6)
#define IO_IIC_CARD_SDA_DIR_IN      PORT1InputConfig(BIT2);PMC1ClearBit(BIT2);PFSEG4ClearBit(BIT6)
#define IO_IIC_CARD_SDA_1           PORT1SetBit(BIT2)
#define IO_IIC_CARD_SDA_0           PORT1ClearBit(BIT2)
#define IO_IIC_CARD_SDA_READ        PORT1ReadBit(BIT2)

//#define IO_VBB_CHK_EN_DIR_OUT       PORT4OutputConfig(BIT5);PMC4ClearBit(BIT5)
//#define IO_VBB_CHK_EN_1             PORT4SetBit(BIT5)
//#define IO_VBB_CHK_EN_0             PORT4ClearBit(BIT5)

#define IO_HALL1_READ               PORT0ReadBit(BIT2)
#define IO_HALL2_READ               PORT0ReadBit(BIT1)

#define IO_EEP_POW_DIR_OUT          PORT0OutputConfig(BIT5);PFSEG6ClearBit(BIT1)
#define IO_EEP_POW_1                PORT0SetBit(BIT5)
#define IO_EEP_POW_0                PORT0ClearBit(BIT5)
#define IO_EEP_POW_PullUp           PORT0PullUpBit(BIT5)
#define IO_COM_SCL_DIR_OUT      PORT0OutputConfig(BIT4);PFSEG6ClearBit(BIT0)
#define IO_COM_SCL_1            PORT0SetBit(BIT4)
#define IO_COM_SCL_0            PORT0ClearBit(BIT4)
#define IO_COM_SDA_DIR_OUT      PORT0OutputConfig(BIT3);PFSEG5ClearBit(BIT7)
#define IO_COM_SDA_DIR_IN       PORT0InputConfig(BIT3);PFSEG5ClearBit(BIT7)
#define IO_COM_SDA_1            PORT0SetBit(BIT3) 
#define IO_COM_SDA_0            PORT0ClearBit(BIT3)
#define IO_COM_SDA_READ         PORT0ReadBit(BIT3)

#define IO_ESAM_POW_DIR_OUT      PORT0OutputConfig(BIT0);PFSEG5ClearBit(BIT4)
#define IO_ESAM_POW_1            PORT0SetBit(BIT0)
#define IO_ESAM_POW_0            PORT0ClearBit(BIT0)
#define IO_ESAM_SCL_DIR_OUT      PORT1OutputConfig(BIT5);PFSEG5ClearBit(BIT1)
#define IO_ESAM_SCL_1            PORT1SetBit(BIT5)
#define IO_ESAM_SCL_0            PORT1ClearBit(BIT5)
#define IO_ESAM_SDA_DIR_OUT      PORT1OutputConfig(BIT6);PFSEG5ClearBit(BIT2)
#define IO_ESAM_SDA_DIR_IN       PORT1InputConfig(BIT6);PFSEG5ClearBit(BIT2)
#define IO_ESAM_SDA_1            PORT1SetBit(BIT6) 
#define IO_ESAM_SDA_0            PORT1ClearBit(BIT6)
#define IO_ESAM_SDA_READ         PORT1ReadBit(BIT6)
#define IO_ESAM_RST_DIR_OUT     PORT1OutputConfig(BIT7);PMC5ClearBit(BIT3)
#define IO_ESAM_RST_1           PORT1SetBit(BIT7)
#define IO_ESAM_RST_0           PORT1ClearBit(BIT7)


