#include 	"r_cg_macrodriver.h"
#include    "lib_rs004.h"

//定义各个IO口
#define IO_BEEP_DIR_OUT      PORT4OutputConfig(BIT6);PFSEG3ClearBit(BIT3)
#define IO_BEEP_1            PORT4SetBit(BIT6)
#define IO_BEEP_O            PORT4ClearBit(BIT6)

#define IO_CARD_BSL_READ            PORT4ReadBit(BIT3)
#define IO_CARD_POWCHECK_DIR_IN     //PORT12InputConfig(BIT2)
#define IO_CARD_POWCHECK_READ       PORT12ReadBit(BIT2)
#define IO_CARD_POW_CON_DIR_OUT     PORT4OutputConfig(BIT5);PMC4ClearBit(BIT5);PFSEG3ClearBit(BIT2)
#define IO_CARD_POW_CON_1           PORT4SetBit(BIT5)
#define IO_CARD_POW_CON_0           PORT4ClearBit(BIT5)

#define IO_IIC_CARD_RST_DIR_OUT     PORT4OutputConfig(BIT4);PMC4ClearBit(BIT4)
#define IO_IIC_CARD_RST_1           PORT4SetBit(BIT4)
#define IO_IIC_CARD_RST_0           PORT4ClearBit(BIT4)

#define IO_IIC_CARD_SCL_DIR_OUT     PORT4OutputConfig(BIT2);PMC4ClearBit(BIT2)
#define IO_IIC_CARD_SCL_1           PORT4SetBit(BIT2)
#define IO_IIC_CARD_SCL_0           PORT4ClearBit(BIT2)

#define IO_IIC_CARD_SDA_DIR_OUT     PORT4OutputConfig(BIT1)
#define IO_IIC_CARD_SDA_DIR_IN      PORT4InputConfig(BIT1)
#define IO_IIC_CARD_SDA_1           PORT4SetBit(BIT1)
#define IO_IIC_CARD_SDA_0           PORT4ClearBit(BIT1)
#define IO_IIC_CARD_SDA_READ        PORT4ReadBit(BIT1)

#define IO_M_SLEEP_DIR_OUT          PORT12OutputConfig(BIT7)
#define IO_M_SLEEP_1                PORT12SetBit(BIT7)
#define IO_M_SLEEP_0                PORT12ClearBit(BIT7)
#define IO_M_CTRL1_DIR_OUT          PORT12OutputConfig(BIT6)
#define IO_M_CTRL1_1                PORT12SetBit(BIT6)
#define IO_M_CTRL1_0                PORT12ClearBit(BIT6)
#define IO_M_CTRL2_DIR_OUT          PORT12OutputConfig(BIT5)
#define IO_M_CTRL2_1                PORT12SetBit(BIT5)
#define IO_M_CTRL2_0                PORT12ClearBit(BIT5)

#define IO_HALL1_READ               PORT5ReadBit(BIT3)
#define IO_HALL2_READ               PORT5ReadBit(BIT2)
#define IO_KEY_READ                 PORT0ReadBit(BIT1)

#define IO_VALVE_CHK_POW_DIR_OUT    PORT7OutputConfig(BIT1);PFSEG1ClearBit(BIT5)
#define IO_VALVE_CHK_POW_1          PORT7SetBit(BIT1)
#define IO_VALVE_CHK_POW_0          PORT7ClearBit(BIT1)
#define IO_VALVE_IN_DIR_IN          PORT7InputConfig(BIT0);PFSEG1ClearBit(BIT4)
#define IO_VALVE_IN_READ            PORT7ReadBit(BIT0)
#define IO_GD_EN_DIR_OUT            PORT0OutputConfig(BIT2);PFSEG5ClearBit(BIT6)
#define IO_GD_EN_DIR_IN             PORT0InputConfig(BIT2);PFSEG5ClearBit(BIT6)
#define IO_GD_EN_1                  PORT0SetBit(BIT2)
#define IO_GD_EN_0                  PORT0ClearBit(BIT2)
#define IO_GD_EN_PullUp             PORT0PullUpBit(BIT2)

#define IO_EEP_POW_DIR_OUT          PORT1OutputConfig(BIT1);PMC1ClearBit(BIT1);PFSEG4ClearBit(BIT5)
#define IO_EEP_POW_1                PORT1SetBit(BIT1)
#define IO_EEP_POW_0                PORT1ClearBit(BIT1)
#define IO_EEP_POW_PullUp           PORT1PullUpBit(BIT1)
#define IO_EEP_IIC_SCL_DIR_OUT      PORT2OutputConfig(BIT7);PMC2ClearBit(BIT7);PFSEG4ClearBit(BIT3)
#define IO_EEP_IIC_SCL_1            PORT2SetBit(BIT7)
#define IO_EEP_IIC_SCL_0            PORT2ClearBit(BIT7)
#define IO_EEP_IIC_SDA_DIR_OUT      PORT1OutputConfig(BIT0);PMC1ClearBit(BIT0);PFSEG4ClearBit(BIT4)
#define IO_EEP_IIC_SDA_DIR_IN       PORT1InputConfig(BIT0);PMC1ClearBit(BIT0);PFSEG4ClearBit(BIT4)
#define IO_EEP_IIC_SDA_1            PORT1SetBit(BIT0) 
#define IO_EEP_IIC_SDA_0            PORT1ClearBit(BIT0)
#define IO_EEP_IIC_SDA_READ         PORT1ReadBit(BIT0)

//#define IO_VBB_CHK_EN_DIR_OUT       PORT2OutputConfig(BIT4);PMC2ClearBit(BIT4);PFSEG4ClearBit(BIT0)
//#define IO_VBB_CHK_EN_1             PORT2SetBit(BIT4)
//#define IO_VBB_CHK_EN_0             PORT2ClearBit(BIT4)

#define IO_RF_ACK_DIR_OUT           PORT7OutputConfig(BIT2);PFSEG1ClearBit(BIT6)
#define IO_RF_ACK_DIR_IN            PORT7InputConfig(BIT2);PFSEG1ClearBit(BIT6)
#define IO_RF_ACK_READ              PORT7ReadBit(BIT2)
#define IO_RF_RERCV_DIR_OUT         PORT7OutputConfig(BIT3);PFSEG1ClearBit(BIT7)
#define IO_RF_RERCV_DIR_IN          PORT7InputConfig(BIT3);PFSEG1ClearBit(BIT7)
#define IO_RF_RERCV_1               PORT7SetBit(BIT3) 
#define IO_RF_RERCV_0               PORT7ClearBit(BIT3)
#define IO_RF_SDI_DIR_OUT           PORT7OutputConfig(BIT6);PFSEG2ClearBit(BIT2)
#define IO_RF_SDI_DIR_IN            PORT7InputConfig(BIT6);PFSEG2ClearBit(BIT2)
#define IO_RF_SDI_READ              PORT7ReadBit(BIT6)
#define IO_RF_RFCLK_DIR_OUT         PORT7OutputConfig(BIT5);PFSEG2ClearBit(BIT1)
#define IO_RF_RFCLK_DIR_IN          PORT7InputConfig(BIT5);PFSEG2ClearBit(BIT1)
#define IO_RF_RFCLK_READ            PORT7ReadBit(BIT5)
#define IO_RF_SDO_DIR_OUT           PORT7OutputConfig(BIT4);PFSEG2ClearBit(BIT0)
#define IO_RF_SDO_DIR_IN            PORT7InputConfig(BIT4);PFSEG2ClearBit(BIT0)
#define IO_RF_SDO_1                 PORT7SetBit(BIT4) 
#define IO_RF_SDO_0                 PORT7ClearBit(BIT4)
#define IO_RF_RST_DIR_OUT           PORT7OutputConfig(BIT7);PFSEG2ClearBit(BIT3)
#define IO_RF_RST_DIR_IN            PORT7InputConfig(BIT7);PFSEG2ClearBit(BIT3)
#define IO_RF_RST_1                 PORT7SetBit(BIT7) 
#define IO_RF_RST_0                 PORT7ClearBit(BIT7)
#define IO_RF_SCK_DIR_OUT           PORT3OutputConfig(BIT0);PFSEG2ClearBit(BIT4)
#define IO_RF_SCK_DIR_IN            PORT3InputConfig(BIT0);PFSEG2ClearBit(BIT4)
#define IO_RF_SCK_1                 PORT3SetBit(BIT0) 
#define IO_RF_SCK_0                 PORT3ClearBit(BIT0)
#define IO_RF_NSS_DIR_OUT           PORT3OutputConfig(BIT1);PFSEG2ClearBit(BIT5)
#define IO_RF_NSS_DIR_IN            PORT3InputConfig(BIT1);PFSEG2ClearBit(BIT5)
#define IO_RF_NSS_1                 PORT3SetBit(BIT1) 
#define IO_RF_NSS_0                 PORT3ClearBit(BIT1)
#define IO_RF_RFTX_DIR_OUT          PORT3OutputConfig(BIT2);PFSEG2ClearBit(BIT6)
#define IO_RF_RFTX_DIR_IN           PORT3InputConfig(BIT2);PFSEG2ClearBit(BIT6)
#define IO_RF_RFTX_1                PORT3SetBit(BIT2) 
#define IO_RF_RFTX_0                PORT3ClearBit(BIT2)
#define IO_RF_RFRX_DIR_OUT          PORT3OutputConfig(BIT3);PFSEG2ClearBit(BIT7)
#define IO_RF_RFRX_DIR_IN           PORT3InputConfig(BIT3);PFSEG2ClearBit(BIT7)
#define IO_RF_RFRX_1                PORT3SetBit(BIT3) 
#define IO_RF_RFRX_0                PORT3ClearBit(BIT3)
#define IO_RF_RFDIO_DIR_OUT         PORT3OutputConfig(BIT4);PFSEG3ClearBit(BIT0)
#define IO_RF_RFDIO_DIR_IN          PORT3InputConfig(BIT4);PFSEG3ClearBit(BIT0)
#define IO_RF_RFDIO_1               PORT3SetBit(BIT4) 
#define IO_RF_RFDIO_0               PORT3ClearBit(BIT4)
#define IO_RF_RSSI_DIR_OUT          PORT3OutputConfig(BIT5);PFSEG3ClearBit(BIT1)
#define IO_RF_RSSI_DIR_IN           PORT3InputConfig(BIT5);PFSEG3ClearBit(BIT1)
#define IO_RF_RSSI_READ             PORT3ReadBit(BIT5)



